# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'jwTextFiled' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jwTextFiled

  target 'jwTextFiledTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jwTextFiledUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod ‘Masonry’

end
